sudo: required
services:
  - docker
language: python
python:
  - "2.7"

env:
  - IGNORE_DOCKER_VERSION=true PYTHONUNBUFFERED=true

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - pip install pip --upgrade
  - pip install git+https://github.com/timothyb89/dbuild.git
  - pip install google-cloud-storage
  - docker --version
  - docker-compose --version
  - ifconfig
  - eth0_ipaddr=$(ifconfig ens4 | awk '{ print $2}' | grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
  - echo "Replacing ip addresses in .env file with dynamic travis eth0 ip:" $eth0_ipaddr
  - sed -i -e "s/\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}/$eth0_ipaddr/g" ".env"
  - cat .env

jobs:
  include:
    - stage: metrics-pipeline
      script: python ci.py metrics
    - stage: logs-pipeline
      script: python ci.py logs False
